# 主任务
process:
  # 工作台爆炸的延时, 单位是毫秒
  # 默认为 3000
  delay: 3000
  # 工作台爆炸的威力
  # 默认为 5
  power: 5

# 警告
warning:
  # 是否开启声音警报
  # 默认为 true
  tick-sound: true
  # 提示信息
  # 设置为空表示不提示
  # 可用的占位符:
  #   {time} 表示剩余时间
  message: '&c还有 &l&e{time} &c秒爆炸！'
