# 主任务
process:
  # 工作台爆炸的延时, 单位是毫秒
  # 默认为 5000
  delay: 5000
  # 工作台爆炸的威力
  # 默认为 8
  power: 8

# 警告
warning:
  # 提醒间隔, 单位是毫秒
  # 默认为 1000
  interval: 1000
  # 是否开启声音警报
  # 默认为 true
  tick-sound: true
  # 提示信息
  # 设置为空表示不提示
  # 可用的占位符:
  #   {time} 表示剩余时间
  #   {player} 表示玩家名
  #   {x} 表示方块坐标 X
  #   {y} 表示方块坐标 Y
  #   {z} 表示方块坐标 Z
  message: '&c还有 &l&e{time} &c秒爆炸！'
